"""add deleted_at

Revision ID: 314a40d506b8
Revises: 0c404f371d80
Create Date: 2026-05-14 20:39:16.679295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314a40d506b8'
down_revision: Union[str, Sequence[str], None] = '0c404f371d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_chunks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('ingestion_jobs', 'deleted_at')
    op.drop_column('document_chunks', 'deleted_at')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_messages', 'deleted_at')
    # ### end Alembic commands ###
